version: '3'
services:
#  nginx:
#    restart: always
#    build:
#      context: ../Nginx
#    ports:
#      - '3000:80'
#    depends_on:
#      - tennis_league_react
#      - tennis_league_spring
#    networks:
#      - frontend
#      - backend

  mongo:
    image: mongo
    ports:
      - "27027:27017"
    networks:
      - backend

  tennis_league_react:
    build:
      context: ../tennisLeague
    ports:
      - "5173:5173"
    networks:
      - frontend
    environment:
      - WDS_SOCKET_PORT=0
    depends_on:
      - tennis_league_spring

  tennis_league_spring:
    build:
      context: .
    env_file: .env
    environment:
      - JWT_KEY=${JWT_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${REGION}
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/players
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - mongo

networks:
  frontend:
  backend:
