server:
  port: 9090

spring:
  data:
    mongodb:
      uri: ${spring.data.mongodb.uri}
      auto-index-creation: true

Jwt:
  secret:
    key: ${JWT_KEY}

aws:
  credentials:
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3:
    buckets:
      customer: tennisleaguebucket


