server:
  port: 9090

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/players
      auto-index-creation: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 3MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: tennisclub.biz@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


logging:
  level:
    org.springframework.security: TRACE

Jwt:
  secret:
    key: ${JWT_KEY}

aws:
  credentials:
    profile: default
  region: eu-north-1
  s3:
    buckets:
      customer: tennisleaguebucket


