server:
  port: 9090

spring:
  data:
    mongodb:
#      uri: mongodb+srv://emiresen:1234@tennisapp.1hde0.mongodb.net/?retryWrites=true&w=majority&appName=tennisapp
#      database: tennisapp

      auto-index-creation: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 3MB


#logging:
#  level:
#    org.springframework.security: TRACE

Jwt:
  secret:
    key: ${JWT_KEY}

aws:
  credentials:
    profile: default
  region: eu-north-1
  s3:
    buckets:
      customer: tennisleaguebucket
