server:
  port: 9090

spring:
  data:
    mongodb:
      uri: ${spring.data.mongodb.uri}
      auto-index-creation: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 3MB

logging:
  level:
    org.springframework.security: TRACE

Jwt:
  secret:
    key: ${JWT_KEY}

aws:
  region: ${AWS_REGION}
  s3:
    buckets:
      customer: ${AWS_BUCKET_NAME}
  credentials:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}


