server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/players
      auto-index-creation: true

logging:
  level:
    org.springframework.security: TRACE

Jwt:
  secret:
    key: ${JWT_KEY}

aws:
  region: eu-north-1
  s3:
    buckets:
      customer: tennisleaguebucket



